[project]
name = "ann"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "streamlit>=1.9.0",
    "tensorflow>=2.20.0",
]
